[1;31mW[0m[1;32mE[0m[1;33mL[0m[1;34mC[0m[1;35mO[0m[1;36mM[0m[1;37mE[0m [1;32mT[0m[1;33mO[0m [1;34mQ[0m[1;35mW[0m[1;36mI[0m[1;37mR[0m[1;32mK[0m[1;33mL[0m[1;34mE[0m
-----------------
Menu
----
1. New Game
2. Load Game
3. Credits (Show student information)
4. Quit
> Starting a New Game
Enter a name for player 1 (uppercase characters only):
> Enter a name for player 2 (uppercase characters only):
> Let's Play!
    1  2  3  4  5  6  7  8  9 
 A|  |  |  |  |  |  |  |  |  |
 B|  |  |  |  |  |  |  |  |  |
 C|  |  |  |  |  |  |  |  |  |
 D|  |  |  |  |  |  |  |  |  |
 E|  |  |  |  |  |  |  |  |  |
 F|  |  |  |  |  |  |  |  |  |
 G|  |  |  |  |  |  |  |  |  |
 H|  |  |  |  |  |  |  |  |  |
 I|  |  |  |  |  |  |  |  |  |
LACHLAN, it's your turn!
Score for LACHLAN: 0
Score for ALLEN: 0
Your hand: R4, R4, R2, P4, G4, P4
> Tile is not in deck
    1  2  3  4  5  6  7  8  9 
 A|  |  |  |  |  |  |  |  |  |
 B|  |  |  |  |  |  |  |  |  |
 C|  |  |  |  |  |  |  |  |  |
 D|  |  |  |  |  |  |  |  |  |
 E|  |  |  |  |  |  |  |  |  |
 F|  |  |  |  |  |  |  |  |  |
 G|  |  |  |  |  |  |  |  |  |
 H|  |  |  |  |  |  |  |  |  |
 I|  |  |  |  |  |  |  |  |  |
LACHLAN, it's your turn!
Score for LACHLAN: 0
Score for ALLEN: 0
Your hand: R4, R4, R2, P4, G4, P4
> Goodbye
